#! /usr/bin/env bash

## Initialize CMSSW
rm -rf CMSSW/src
source /cvmfs/cms.cern.ch/cmsset_default.sh
export $SCRAM_ARCH=slc6_amd64_gcc491
scram project -n CMSSW CMSSW CMSSW_7_3_0_pre1
cd CMSSW/src
cmsenv

## Retrieve the test version of the emulator
git cms-merge-topic --unsafe tstreble:${CMSSW_VERSION}_Thomas

cd -

## Retrieve the submodules
git checkout CMSSW/src
git submodule init
git submodule update

## Compile CMSSW
cd CMSSW/src/
scram b -j4

##  Compile the emulator wrapper
cd ../../L1TEmulatorWrapper 
git checkout test-eg-firmware-CMSSW_7_3_0_pre1
make
source wrapenv
cd ..




