#! /usr/bin/env bash

## Initialize CMSSW
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=slc6_amd64_gcc491
scram project -n CMSSW CMSSW CMSSW_7_5_0_pre1
cd CMSSW/src
cmsenv

## Retrieve the test version of the emulator
echo
echo "#####################"
echo "Retrieving emulator"
echo "#####################"
echo
git cms-merge-topic --unsafe jbsauvan:jbsauvan-l1t-devel-${CMSSW_VERSION}

cd -

## Retrieve the submodules
echo
echo "#####################"
echo "Retrieving submodules"
echo "#####################"
echo
git submodule init
#git submodule update
git submodule update --remote

## Compile CMSSW
echo
echo "#####################"
echo "Compiling CMSSW"
echo "#####################"
echo
cd CMSSW/src/
scram b -j4

##  Compile the emulator wrapper
echo
echo "#####################"
echo "Compiling the emulator wrapper"
echo "#####################"
echo
cd ../../L1TEmulatorWrapper 
make
source wrapenv
cd ..


## Compile the AnHiMa analyses
echo
echo "#####################"
echo "Compiling performance analyses"
echo "#####################"
echo
cd L1Trigger-AnalysisHistoMaker 
ANALYSES=`ls -l | egrep '^d' | awk '{print $9}'`
for ANALYSIS in $ANALYSES
do
	cd ${ANALYSIS}
	if [ -e Makefile ]
	then
		make -j4
	fi
	cd -
done



